version: 2.1

orbs:
  nx: nrwl/nx@1.5.1
  jq: circleci/jq@3.0.0

jobs:
  main:
    docker:
      - image: node:20
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install --frozen-lockfile
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - nx/set-shas
      - run:
          name: Initialize DTE agents
          command: pnpm nx-cloud start-ci-run
      - run:
          name: Run tasks in DTE
          command: |
            pnpm nx affected --base=$NX_BASE --head=$NX_HEAD -t lint,test,build --parallel=3 --configuration=ci
      - run:
          name: Run deploy tasks in DTE
          command: |
            pnpm nx affected --base=$NX_BASE --head=$NX_HEAD -t deploy --parallel=3 --configuration=ci -- --project-name=$CLOUDFLARE_PAGES_PROJECT_NAME --branch=$CIRCLE_BRANCH
      - run:
          name: Stop all running agents for this CI run
          when: always
          command: pnpm nx-cloud stop-all-agents
      - jq/install:
          version: jq-1.7
      - run:
          name: Post Stats to GitHub PR
          command: |
            if [ $(pnpm nx show projects --affected -p "web") != "web" ]; then
              pr_response=$(curl --location --request GET "https://api.github.com/repos/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/pulls?head=$CIRCLE_PROJECT_USERNAME:$CIRCLE_BRANCH&state=open" -u $GH_USERNAME:$GH_TOKEN)

              if [ $(echo $pr_response | jq length) -eq 0 ]; then
                echo "No PR found to update"
              else
                pr_comment_url=$(echo $pr_response | jq -r ".[]._links.comments.href")
              fi

              url_response=$(curl -H 'Authorization: Bearer $CLOUDFLARE_API_TOKEN' 'https://api.cloudflare.com/client/v4/accounts/$CLOUDFLARE_ACCOUNT_ID/pages/projects/$CLOUDFLARE_PAGES_PROJECT_NAME/deployments' | jq -r '.result[0].url')

              body=$(printf "**Preview URL**: %s" $url_response)

              curl --location --request POST "$pr_comment_url" \
              -u $GH_USERNAME:$GH_TOKEN \
              --header 'Content-Type: application/json' \
              --data-raw "{
                \"body\": \"$body\"
              }"
            else
              echo "Not a web deployments"
            fi

  agent:
    docker:
      - image: node:20
    parameters:
      ordinal:
        type: integer
    steps:
      - checkout
      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
      - run:
          name: Install pnpm package manager
          command: |
            corepack enable
            corepack prepare pnpm@latest-8 --activate
      - run:
          name: Install Dependencies
          command: |
            pnpm install --frozen-lockfile
      - save_cache:
          name: Save pnpm Package Cache
          key: pnpm-packages-{{ checksum "pnpm-lock.yaml" }}
          paths:
            - node_modules
      - run:
          name: Run DTE tasks
          command: pnpm nx-cloud start-agent
          no_output_timeout: 10m
workflows:
  build:
    jobs:
      - agent:
          matrix:
            parameters:
              ordinal: [1, 2, 3]
      - main
