version: 2.1
orbs:
  nx: nrwl/nx@1.5.1
jobs:
  main:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - run: npm ci
      # Get latest complete build
      - nx/set-shas

      # Tell Nx Cloud to use DTE and stop agents when the build tasks are done
      - run: npx nx-cloud start-ci-run --stop-agents-after=build
      # Send logs to Nx Cloud for any CLI command
      - run: npx nx-cloud record -- npx nx format:check
      # Lint, test and build on agent jobs everything affected by a change
      - run: npx nx affected --base=$NX_BASE --head=$NX_HEAD -t lint,test,build --parallel=2 --configuration=ci
  agent:
    docker:
      - image: cimg/node:lts-browsers
    parameters:
      ordinal:
        type: integer
    steps:
      - checkout
      - run: npm ci
      # Wait for instructions from Nx Cloud
      - run:
          command: npx nx-cloud start-agent
          no_output_timeout: 60m
workflows:
  build:
    jobs:
      - agent:
          matrix:
            parameters:
              ordinal: [1, 2, 3]
      - main
